name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload source code as artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  setup:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Install dependencies
        run: |
          if [ -f lambda/requirements.txt ]; then pip install -r lambda/requirements.txt; fi

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r9 ../lambda_uploaded_video.zip .

      - name: Upload Lambda zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-zip
          path: lambda_uploaded_video.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download Lambda Artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda-zip

      - name: Upload Lambda to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
        run: |
          aws s3 cp lambda_uploaded_video.zip s3://fonte-lambda-uploaded-video/lambda_uploaded_video.zip

      - name: Update Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
        run: |
          aws lambda update-function-code --function-name uploaded_video --s3-bucket fonte-lambda-uploaded-video --s3-key lambda_uploaded_video.zip

  post_actions:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Clean up local files
        run: |
          rm -f lambda_uploaded_video.zip
